### ISSUE TITLE
don't run

### ISSUE THREAD

**Issue by GraemRus** [wkpark/uddetailer#43]
![image](https://github.com/wkpark/uddetailer/assets/116455124/3d3be6fc-a7b4-4124-8ddf-2ad402ded6ca)
don't run

**Comment by wkpark** [comment]
thank you for your reporting!

**Comment by wkpark** [comment]
fixed by commit https://github.com/wkpark/uddetailer/commit/d19fd08dec25a5bd3b89b7647036839aa7f8e6a5

**Comment by wkpark** [comment]
another install related found and fixed https://github.com/wkpark/uddetailer/issues/45
