### ISSUE TITLE
What is this addon?

### ISSUE THREAD

**Issue by Adzido** [wkpark/uddetailer#55]
I read the description and I'm not entirely sure what this plug-in does. Doesn't it do the same thing as ADetailer? That one also selects regions and fixes them.
This should be used instead of ADetailer, yes?

Forgive me for the question but I am a novice in SD.

**Comment by wkpark** [comment]
this is a [DDetailer](https://github.com/dustysys/ddetailer) fork. yes. do the same thing as ADetailer + alpha.
