### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.core'

### ISSUE THREAD

**Issue by thejohnd0e** [wkpark/uddetailer#70]
Hi, I got it now. I think it's because it's incompatible with Tensor RT.

![Screenshot - 2024-01-15 20 01 24](https://github.com/wkpark/uddetailer/assets/115493464/d617f4de-e538-44b3-8558-c325cad88622)

![Screenshot - 2024-01-15 20 04 38](https://github.com/wkpark/uddetailer/assets/115493464/7dddc728-ce39-49b2-a170-17ad1a2db396)

**Comment by wkpark** [comment]
I've got the same error recently with the newest torch-2.3.0 and forgot to push fixes. fixed now

**Comment by thejohnd0e** [comment]
After the update that error disappeared but another warning appeared


![Screenshot - 2024-01-16 14 25 22](https://github.com/wkpark/uddetailer/assets/115493464/08ab367c-47e8-431e-a5ae-88ffac68a9c7)

**Comment by wkpark** [comment]
that's ok. it indicates that it fails to load `mmdet.core` for some reasons. (so, mmdet/mmyolo models will not work. you can use ultralytics(yolov8) or mediapipe models in this case)

- `mmdet.core` is failed to load/import another dependent dll files.
- for example,`mmdet.core` is not supported with the latest torch 2.3.0.

**Comment by thejohnd0e** [comment]
Despite this warning the extension works well with all models, so TY!
