### ISSUE TITLE
BUG: all_hr_prompts error in AUTOMATIC1111 1.9.0 RC

### ISSUE THREAD

**Issue by jgrubs1** [wkpark/uddetailer#80]
In AUTOMATIC1111 1.9.0 RC, the extension throws the following error on each detection. Apparently, the way "all_hr_prompts" is handled had changed in the 1.9.0.

`*** Error creating infotext for key "Hires prompt"
    Traceback (most recent call last):
      File "S:\stable-diffusion\sd-webui\webui\modules\processing.py", line 809, in create_infotext
        generation_params[key] = value(**locals())
      File "S:\stable-diffusion\sd-webui\webui\modules\processing.py", line 1259, in get_hr_prompt
        hr_prompt = p.all_hr_prompts[index]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'all_hr_prompts'

---
*** Error creating infotext for key "Hires negative prompt"
    Traceback (most recent call last):
      File "S:\stable-diffusion\sd-webui\webui\modules\processing.py", line 809, in create_infotext
        generation_params[key] = value(**locals())
      File "S:\stable-diffusion\sd-webui\webui\modules\processing.py", line 1263, in get_hr_negative_prompt
        hr_negative_prompt = p.all_hr_negative_prompts[index]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'all_hr_negative_prompts'`

**Comment by aoleg** [comment]
Could be caused by this https://github.com/adieyal/sd-dynamic-prompts/issues/752
Try updating [sd-dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts) and see if it fixes it.

**Comment by wkpark** [comment]
> Could be caused by this [adieyal/sd-dynamic-prompts#752](https://github.com/adieyal/sd-dynamic-prompts/issues/752) Try updating [sd-dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts) and see if it fixes it.

thank you for your information!

yes this is not a bug of uddetaier.
The latest sd-dynamic-prompts extension already has fixed this bug.
