### ISSUE TITLE
How to get the extenstion to detect faces?

### ISSUE THREAD

**Issue by koopa990** [wkpark/uddetailer#87]
Am I supposed to see a masked color-coded box around a subject's face, or manually inpaint?

**Comment by wkpark** [comment]
![image](https://github.com/wkpark/uddetailer/assets/232347/2494c8c6-11d8-441a-b926-b7858f086409)

did you activate uddetailer extension? or uddetailer correctly shown at the extension tab?

**Comment by koopa990** [comment]
> ![image](https://github.com/wkpark/uddetailer/assets/232347/2494c8c6-11d8-441a-b926-b7858f086409)
> 
> did you activate uddetailer extension? or uddetailer correctly shown at the extension tab?

I  found out the reason why the box doesn't appear is due to Forge communication error with the wxtensionc
